version: '3'
services:
  server:
    container_name: 'my-server'
    restart: always
    build: .
    ports:
      - "5000:5001"
    links:
      - mongo
    volumes:
      - .:/usr/src/app
  mongo:
    container_name: "my-database"
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - ./src/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro